$imgDir = "img"
$vidDir = "vid"
$dataFile = "data.js"

function Get-MediaData($dir, $extensions) {
    if (-not (Test-Path $dir)) { return "[]" }
    
    $files = Get-ChildItem -Path $dir | Where-Object { $extensions -contains $_.Extension.ToLower() }
    $data = @()
    $i = 1
    
    foreach ($file in $files) {
        $name = $file.BaseName
        # Better title cleaning: remove "WhatsApp Image/Video" and date/time patterns
        $title = $name -replace "^WhatsApp (Image|Video) [\d-]* at ", "" -replace "[\d.]* [AP]M$", "" -replace "-", " " -replace "_", " "
        if ($title -eq "") { $title = "Media $i" }
        $date = $file.LastWriteTime.ToString("MMM d, yyyy")
        $url = "$dir/$($file.Name)"
        
        $item = @{
            id = $i
            url = $url
            title = $title.Trim()
            date = $date
        }
        
        if ($dir -eq "vid") {
            $item["duration"] = "0:00"
            $item["tags"] = ""
            $item["thumbnail"] = "img/" + ($name -replace "Video", "Image") + ".jpg" # Guessing thumbnail path
        }
        
        $data += $item
        $i++
    }
    
    return $data | ConvertTo-Json -Depth 10
}

$photoDataJson = Get-MediaData $imgDir @(".jpg", ".jpeg", ".png", ".webp", ".gif")
$videoDataJson = Get-MediaData $vidDir @(".mp4", ".webm", ".ogg", ".mov")

$content = @"
// ============================================================
// BMail Media Data — AUTO-GENERATED BY sync.ps1
// ============================================================

const photosData = $photoDataJson;

const videosData = $videoDataJson;
"@

Set-Content -Path $dataFile -Value $content
Write-Host "Successfully synced media data to $dataFile!" -ForegroundColor Green
