$imgDir = "img"
$vidDir = "vid"
$dataFile = "data.js"

function Get-MediaData($dir, $extensions) {
    if (-not (Test-Path $dir)) { return "[]" }
    
    $files = Get-ChildItem -Path $dir | Where-Object { $extensions -contains $_.Extension.ToLower() }
    $data = @()
    $i = 1
    
    foreach ($file in $files) {
        $name = $file.BaseName
        # Even better title cleaning: extract date and make it pretty
        if ($name -match "(\d{4}-\d{2}-\d{2}) at (\d{1,2}\.\d{2}\.\d{2} [AP]M)") {
            $datePart = $matches[1]
            $timePart = $matches[2] -replace "\.", ":"
            $title = [DateTime]::ParseExact($datePart, "yyyy-MM-dd", $null).ToString("MMM d, yyyy") + " - " + $timePart
        } else {
            $title = $name -replace "^WhatsApp (Image|Video) ", "" -replace " at ", " " -replace "-", " " -replace "_", " "
        }
        $title = $title.Trim()
        if ($title -eq "") { $title = "Media $i" }
        $date = $file.LastWriteTime.ToString("MMM d, yyyy")
        $url = "$dir/$($file.Name)"
        
        $item = @{
            id = $i
            url = $url
            title = $title.Trim()
            date = $date
        }
        
        if ($dir -eq "vid") {
            $item["duration"] = "0:00"
            $item["tags"] = ""
            $item["thumbnail"] = "" # No longer needed, UI uses video itself
        }
        
        $data += $item
        $i++
    }
    return $data | ConvertTo-Json -Depth 10
}

$photoDataJson = Get-MediaData $imgDir @(".jpg", ".jpeg", ".png", ".webp", ".gif")
$videoDataJson = Get-MediaData $vidDir @(".mp4", ".webm", ".ogg", ".mov")

# Fix encoding issues (like \u0026 for &)
$photoDataJson = $photoDataJson -replace "\\u0026", "&"
$videoDataJson = $videoDataJson -replace "\\u0026", "&"

$content = @"
// ============================================================
// BMail Media Data — AUTO-GENERATED BY sync.ps1
// ============================================================

const photosData = $photoDataJson;

const videosData = $videoDataJson;
"@

Set-Content -Path $dataFile -Value $content
Write-Host "Successfully synced media data to $dataFile!" -ForegroundColor Green


# powershell -ExecutionPolicy Bypass -File sync.ps1