const fs = require('fs');
const path = require('path');

const IMG_DIR = path.join(__dirname, 'img');
const VID_DIR = path.join(__dirname, 'vid');
const DATA_FILE = path.join(__dirname, 'data.js');

function getFiles(dir, extensions) {
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir)
        .filter(file => extensions.includes(path.extname(file).toLowerCase()))
        .map((file, index) => {
            const ext = path.extname(file);
            const name = path.basename(file, ext);
            // Clean up name for title: remove WhatsApp prefixes, replace dashes with spaces
            const title = name.replace(/WhatsApp (Image|Video) \d{4}-\d{2}-\d{2} at /, '')
                .replace(/-/g, ' ')
                .replace(/_/g, ' ')
                .trim();

            return {
                id: index + 1,
                url: `${path.basename(dir)}/${file}`,
                title: title || `Media ${index + 1}`,
                date: new Date(fs.statSync(path.join(dir, file)).mtime).toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric'
                })
            };
        });
}

const photos = getFiles(IMG_DIR, ['.jpg', '.jpeg', '.png', '.webp', '.gif']);
const videos = getFiles(VID_DIR, ['.mp4', '.webm', '.ogg', '.mov']);

// Special handling for videos: add default values for thumbnail, duration, etc.
const videoData = videos.map(v => ({
    ...v,
    thumbnail: v.url.replace('vid/', 'img/').replace(/\.[^/.]+$/, ".jpg"), // Attempt to find a matching thumbnail or use a default
    duration: "0:00", // Would require ffmpeg to automate, keeping manual placeholder
    tags: ""
}));

const content = `// ============================================================
// BMail Media Data — AUTO-GENERATED BY sync.js
// ============================================================

const photosData = ${JSON.stringify(photos, null, 4)};

const videosData = ${JSON.stringify(videoData, null, 4)};
`;

fs.writeFileSync(DATA_FILE, content);
console.log('Successfully synced media data!');
